name: checout_trainer
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  linear_timer: ^2.0.0

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/checkout_trainer_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/dartbord.jpg
    - assets/icon/checkout_trainer_logo.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700